import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    // border

    func borderBorderWidth() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 2) 
    }
}