import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {  

    // Border Radius

    func borderBorderRadiusButtonBorderRadius() -> some View {
        return self.cornerRadius(15) 
    }
}