import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {  

    // Border Radius

    // border

    func borderBorderRadiusborderRadius() -> some View {
        return self.cornerRadius(40) 
    }
}