import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // color

        // button

        // background
        public let colorbuttonbackgroundPrimary = Color(.sRGB, red: 255/255, green: 194/255, blue: 14/255, opacity: 1) 
        public let colorbuttonbackgroundSecondary = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorbuttonbackgroundTertiary = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // boxshadow
        public let colorbuttonboxshadowDefault = Color(.sRGB, red: 255/255, green: 194/255, blue: 14/255, opacity: 1) 
        public let colorbuttonboxshadowActive = Color(.sRGB, red: 255/255, green: 231/255, blue: 45/255, opacity: 1) 
    }
}